"""empty message

Revision ID: 7444cad42e6d
Revises: 
Create Date: 2021-07-13 15:56:40.266884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7444cad42e6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionario')
    # ### end Alembic commands ###
